services:
  db:
    image: postgres:16-alpine
    container_name: kairos-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kairos
      - POSTGRES_PASSWORD=kairos
      - POSTGRES_DB=kairos
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: kairos-redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  worker:
    build:
      context: .
      args:
        CMD_PATH: cmd/worker
    container_name: kairos-worker
    environment:
      NODE_ID: docker-worker-1
      TENANT_ID: default
      REDIS_ADDR: redis:6379
      POSTGRES_DSN: postgres://kairos:kairos@db:5432/kairos
      OTEL_EXPORTER_OTLP_ENDPOINT: jaeger:4318
    ports:
      - "2112:2112"
    depends_on:
      - redis
      - db
      - jaeger

  prometheus:
    image: prom/prometheus:latest
    container_name: kairos-prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - worker

  grafana:
    image: grafana/grafana:latest
    container_name: kairos-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: kairos
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: kairos-jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686" # jaeger-ui
      - "4318:4318" # otlp http receiver
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:
  prometheus-data:
  grafana-data:
