// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0--rc1
// source: proto/kairos/v1/kairos.proto

package kairospb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_HIGH        Priority = 1
	Priority_PRIORITY_DEFAULT     Priority = 2
	Priority_PRIORITY_LOW         Priority = 3
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_HIGH",
		2: "PRIORITY_DEFAULT",
		3: "PRIORITY_LOW",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_HIGH":        1,
		"PRIORITY_DEFAULT":     2,
		"PRIORITY_LOW":         3,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kairos_v1_kairos_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_proto_kairos_v1_kairos_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_proto_kairos_v1_kairos_proto_rawDescGZIP(), []int{0}
}

type EnqueueRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload        []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	MaxAttempts    int32                  `protobuf:"varint,3,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	Priority       Priority               `protobuf:"varint,4,opt,name=priority,proto3,enum=kairos.v1.Priority" json:"priority,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // optional; empty means no idempotency check
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_proto_kairos_v1_kairos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_v1_kairos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_kairos_v1_kairos_proto_rawDescGZIP(), []int{0}
}

func (x *EnqueueRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EnqueueRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EnqueueRequest) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *EnqueueRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *EnqueueRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type EnqueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Enqueued      bool                   `protobuf:"varint,2,opt,name=enqueued,proto3" json:"enqueued,omitempty"` // false if skipped due to a duplicate idempotency key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_proto_kairos_v1_kairos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_v1_kairos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_proto_kairos_v1_kairos_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *EnqueueResponse) GetEnqueued() bool {
	if x != nil {
		return x.Enqueued
	}
	return false
}

type GetQueueDepthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueDepthRequest) Reset() {
	*x = GetQueueDepthRequest{}
	mi := &file_proto_kairos_v1_kairos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueDepthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueDepthRequest) ProtoMessage() {}

func (x *GetQueueDepthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_v1_kairos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueDepthRequest.ProtoReflect.Descriptor instead.
func (*GetQueueDepthRequest) Descriptor() ([]byte, []int) {
	return file_proto_kairos_v1_kairos_proto_rawDescGZIP(), []int{2}
}

type GetQueueDepthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DepthByPriority map[string]int64       `protobuf:"bytes,1,rep,name=depth_by_priority,json=depthByPriority,proto3" json:"depth_by_priority,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetQueueDepthResponse) Reset() {
	*x = GetQueueDepthResponse{}
	mi := &file_proto_kairos_v1_kairos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueDepthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueDepthResponse) ProtoMessage() {}

func (x *GetQueueDepthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_v1_kairos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueDepthResponse.ProtoReflect.Descriptor instead.
func (*GetQueueDepthResponse) Descriptor() ([]byte, []int) {
	return file_proto_kairos_v1_kairos_proto_rawDescGZIP(), []int{3}
}

func (x *GetQueueDepthResponse) GetDepthByPriority() map[string]int64 {
	if x != nil {
		return x.DepthByPriority
	}
	return nil
}

type ListDeadLetterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeadLetterRequest) Reset() {
	*x = ListDeadLetterRequest{}
	mi := &file_proto_kairos_v1_kairos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeadLetterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeadLetterRequest) ProtoMessage() {}

func (x *ListDeadLetterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_v1_kairos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeadLetterRequest.ProtoReflect.Descriptor instead.
func (*ListDeadLetterRequest) Descriptor() ([]byte, []int) {
	return file_proto_kairos_v1_kairos_proto_rawDescGZIP(), []int{4}
}

func (x *ListDeadLetterRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Attempts      int32                  `protobuf:"varint,5,opt,name=attempts,proto3" json:"attempts,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,6,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	LastError     string                 `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_proto_kairos_v1_kairos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_v1_kairos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_proto_kairos_v1_kairos_proto_rawDescGZIP(), []int{5}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Job) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Job) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *Job) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListDeadLetterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeadLetterResponse) Reset() {
	*x = ListDeadLetterResponse{}
	mi := &file_proto_kairos_v1_kairos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeadLetterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeadLetterResponse) ProtoMessage() {}

func (x *ListDeadLetterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_v1_kairos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeadLetterResponse.ProtoReflect.Descriptor instead.
func (*ListDeadLetterResponse) Descriptor() ([]byte, []int) {
	return file_proto_kairos_v1_kairos_proto_rawDescGZIP(), []int{6}
}

func (x *ListDeadLetterResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type RequeueDeadLetterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequeueDeadLetterRequest) Reset() {
	*x = RequeueDeadLetterRequest{}
	mi := &file_proto_kairos_v1_kairos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequeueDeadLetterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequeueDeadLetterRequest) ProtoMessage() {}

func (x *RequeueDeadLetterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_v1_kairos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequeueDeadLetterRequest.ProtoReflect.Descriptor instead.
func (*RequeueDeadLetterRequest) Descriptor() ([]byte, []int) {
	return file_proto_kairos_v1_kairos_proto_rawDescGZIP(), []int{7}
}

func (x *RequeueDeadLetterRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type RequeueDeadLetterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requeued      bool                   `protobuf:"varint,1,opt,name=requeued,proto3" json:"requeued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequeueDeadLetterResponse) Reset() {
	*x = RequeueDeadLetterResponse{}
	mi := &file_proto_kairos_v1_kairos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequeueDeadLetterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequeueDeadLetterResponse) ProtoMessage() {}

func (x *RequeueDeadLetterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_v1_kairos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequeueDeadLetterResponse.ProtoReflect.Descriptor instead.
func (*RequeueDeadLetterResponse) Descriptor() ([]byte, []int) {
	return file_proto_kairos_v1_kairos_proto_rawDescGZIP(), []int{8}
}

func (x *RequeueDeadLetterResponse) GetRequeued() bool {
	if x != nil {
		return x.Requeued
	}
	return false
}

var File_proto_kairos_v1_kairos_proto protoreflect.FileDescriptor

const file_proto_kairos_v1_kairos_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/kairos/v1/kairos.proto\x12\tkairos.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x01\n" +
	"\x0eEnqueueRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12!\n" +
	"\fmax_attempts\x18\x03 \x01(\x05R\vmaxAttempts\x12/\n" +
	"\bpriority\x18\x04 \x01(\x0e2\x13.kairos.v1.PriorityR\bpriority\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"D\n" +
	"\x0fEnqueueResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1a\n" +
	"\benqueued\x18\x02 \x01(\bR\benqueued\"\x16\n" +
	"\x14GetQueueDepthRequest\"\xbe\x01\n" +
	"\x15GetQueueDepthResponse\x12a\n" +
	"\x11depth_by_priority\x18\x01 \x03(\v25.kairos.v1.GetQueueDepthResponse.DepthByPriorityEntryR\x0fdepthByPriority\x1aB\n" +
	"\x14DepthByPriorityEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"-\n" +
	"\x15ListDeadLetterRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\"\xf4\x01\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\battempts\x18\x05 \x01(\x05R\battempts\x12!\n" +
	"\fmax_attempts\x18\x06 \x01(\x05R\vmaxAttempts\x12\x1d\n" +
	"\n" +
	"last_error\x18\a \x01(\tR\tlastError\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"<\n" +
	"\x16ListDeadLetterResponse\x12\"\n" +
	"\x04jobs\x18\x01 \x03(\v2\x0e.kairos.v1.JobR\x04jobs\"1\n" +
	"\x18RequeueDeadLetterRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"7\n" +
	"\x19RequeueDeadLetterResponse\x12\x1a\n" +
	"\brequeued\x18\x01 \x01(\bR\brequeued*_\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x01\x12\x14\n" +
	"\x10PRIORITY_DEFAULT\x10\x02\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x032\xdc\x02\n" +
	"\rKairosService\x12@\n" +
	"\aEnqueue\x12\x19.kairos.v1.EnqueueRequest\x1a\x1a.kairos.v1.EnqueueResponse\x12R\n" +
	"\rGetQueueDepth\x12\x1f.kairos.v1.GetQueueDepthRequest\x1a .kairos.v1.GetQueueDepthResponse\x12U\n" +
	"\x0eListDeadLetter\x12 .kairos.v1.ListDeadLetterRequest\x1a!.kairos.v1.ListDeadLetterResponse\x12^\n" +
	"\x11RequeueDeadLetter\x12#.kairos.v1.RequeueDeadLetterRequest\x1a$.kairos.v1.RequeueDeadLetterResponseB*Z(github.com/harshalvk/kairos/pkg/kairospbb\x06proto3"

var (
	file_proto_kairos_v1_kairos_proto_rawDescOnce sync.Once
	file_proto_kairos_v1_kairos_proto_rawDescData []byte
)

func file_proto_kairos_v1_kairos_proto_rawDescGZIP() []byte {
	file_proto_kairos_v1_kairos_proto_rawDescOnce.Do(func() {
		file_proto_kairos_v1_kairos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kairos_v1_kairos_proto_rawDesc), len(file_proto_kairos_v1_kairos_proto_rawDesc)))
	})
	return file_proto_kairos_v1_kairos_proto_rawDescData
}

var file_proto_kairos_v1_kairos_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_kairos_v1_kairos_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_kairos_v1_kairos_proto_goTypes = []any{
	(Priority)(0),                     // 0: kairos.v1.Priority
	(*EnqueueRequest)(nil),            // 1: kairos.v1.EnqueueRequest
	(*EnqueueResponse)(nil),           // 2: kairos.v1.EnqueueResponse
	(*GetQueueDepthRequest)(nil),      // 3: kairos.v1.GetQueueDepthRequest
	(*GetQueueDepthResponse)(nil),     // 4: kairos.v1.GetQueueDepthResponse
	(*ListDeadLetterRequest)(nil),     // 5: kairos.v1.ListDeadLetterRequest
	(*Job)(nil),                       // 6: kairos.v1.Job
	(*ListDeadLetterResponse)(nil),    // 7: kairos.v1.ListDeadLetterResponse
	(*RequeueDeadLetterRequest)(nil),  // 8: kairos.v1.RequeueDeadLetterRequest
	(*RequeueDeadLetterResponse)(nil), // 9: kairos.v1.RequeueDeadLetterResponse
	nil,                               // 10: kairos.v1.GetQueueDepthResponse.DepthByPriorityEntry
	(*timestamppb.Timestamp)(nil),     // 11: google.protobuf.Timestamp
}
var file_proto_kairos_v1_kairos_proto_depIdxs = []int32{
	0,  // 0: kairos.v1.EnqueueRequest.priority:type_name -> kairos.v1.Priority
	10, // 1: kairos.v1.GetQueueDepthResponse.depth_by_priority:type_name -> kairos.v1.GetQueueDepthResponse.DepthByPriorityEntry
	11, // 2: kairos.v1.Job.created_at:type_name -> google.protobuf.Timestamp
	6,  // 3: kairos.v1.ListDeadLetterResponse.jobs:type_name -> kairos.v1.Job
	1,  // 4: kairos.v1.KairosService.Enqueue:input_type -> kairos.v1.EnqueueRequest
	3,  // 5: kairos.v1.KairosService.GetQueueDepth:input_type -> kairos.v1.GetQueueDepthRequest
	5,  // 6: kairos.v1.KairosService.ListDeadLetter:input_type -> kairos.v1.ListDeadLetterRequest
	8,  // 7: kairos.v1.KairosService.RequeueDeadLetter:input_type -> kairos.v1.RequeueDeadLetterRequest
	2,  // 8: kairos.v1.KairosService.Enqueue:output_type -> kairos.v1.EnqueueResponse
	4,  // 9: kairos.v1.KairosService.GetQueueDepth:output_type -> kairos.v1.GetQueueDepthResponse
	7,  // 10: kairos.v1.KairosService.ListDeadLetter:output_type -> kairos.v1.ListDeadLetterResponse
	9,  // 11: kairos.v1.KairosService.RequeueDeadLetter:output_type -> kairos.v1.RequeueDeadLetterResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_kairos_v1_kairos_proto_init() }
func file_proto_kairos_v1_kairos_proto_init() {
	if File_proto_kairos_v1_kairos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kairos_v1_kairos_proto_rawDesc), len(file_proto_kairos_v1_kairos_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kairos_v1_kairos_proto_goTypes,
		DependencyIndexes: file_proto_kairos_v1_kairos_proto_depIdxs,
		EnumInfos:         file_proto_kairos_v1_kairos_proto_enumTypes,
		MessageInfos:      file_proto_kairos_v1_kairos_proto_msgTypes,
	}.Build()
	File_proto_kairos_v1_kairos_proto = out.File
	file_proto_kairos_v1_kairos_proto_goTypes = nil
	file_proto_kairos_v1_kairos_proto_depIdxs = nil
}
