// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0--rc1
// source: proto/kairos/v1/kairos.proto

package kairospb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KairosService_Enqueue_FullMethodName           = "/kairos.v1.KairosService/Enqueue"
	KairosService_GetQueueDepth_FullMethodName     = "/kairos.v1.KairosService/GetQueueDepth"
	KairosService_ListDeadLetter_FullMethodName    = "/kairos.v1.KairosService/ListDeadLetter"
	KairosService_RequeueDeadLetter_FullMethodName = "/kairos.v1.KairosService/RequeueDeadLetter"
)

// KairosServiceClient is the client API for KairosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KairosServiceClient interface {
	Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error)
	GetQueueDepth(ctx context.Context, in *GetQueueDepthRequest, opts ...grpc.CallOption) (*GetQueueDepthResponse, error)
	ListDeadLetter(ctx context.Context, in *ListDeadLetterRequest, opts ...grpc.CallOption) (*ListDeadLetterResponse, error)
	RequeueDeadLetter(ctx context.Context, in *RequeueDeadLetterRequest, opts ...grpc.CallOption) (*RequeueDeadLetterResponse, error)
}

type kairosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKairosServiceClient(cc grpc.ClientConnInterface) KairosServiceClient {
	return &kairosServiceClient{cc}
}

func (c *kairosServiceClient) Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueResponse)
	err := c.cc.Invoke(ctx, KairosService_Enqueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kairosServiceClient) GetQueueDepth(ctx context.Context, in *GetQueueDepthRequest, opts ...grpc.CallOption) (*GetQueueDepthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQueueDepthResponse)
	err := c.cc.Invoke(ctx, KairosService_GetQueueDepth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kairosServiceClient) ListDeadLetter(ctx context.Context, in *ListDeadLetterRequest, opts ...grpc.CallOption) (*ListDeadLetterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeadLetterResponse)
	err := c.cc.Invoke(ctx, KairosService_ListDeadLetter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kairosServiceClient) RequeueDeadLetter(ctx context.Context, in *RequeueDeadLetterRequest, opts ...grpc.CallOption) (*RequeueDeadLetterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequeueDeadLetterResponse)
	err := c.cc.Invoke(ctx, KairosService_RequeueDeadLetter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KairosServiceServer is the server API for KairosService service.
// All implementations must embed UnimplementedKairosServiceServer
// for forward compatibility.
type KairosServiceServer interface {
	Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error)
	GetQueueDepth(context.Context, *GetQueueDepthRequest) (*GetQueueDepthResponse, error)
	ListDeadLetter(context.Context, *ListDeadLetterRequest) (*ListDeadLetterResponse, error)
	RequeueDeadLetter(context.Context, *RequeueDeadLetterRequest) (*RequeueDeadLetterResponse, error)
	mustEmbedUnimplementedKairosServiceServer()
}

// UnimplementedKairosServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKairosServiceServer struct{}

func (UnimplementedKairosServiceServer) Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enqueue not implemented")
}
func (UnimplementedKairosServiceServer) GetQueueDepth(context.Context, *GetQueueDepthRequest) (*GetQueueDepthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQueueDepth not implemented")
}
func (UnimplementedKairosServiceServer) ListDeadLetter(context.Context, *ListDeadLetterRequest) (*ListDeadLetterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDeadLetter not implemented")
}
func (UnimplementedKairosServiceServer) RequeueDeadLetter(context.Context, *RequeueDeadLetterRequest) (*RequeueDeadLetterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequeueDeadLetter not implemented")
}
func (UnimplementedKairosServiceServer) mustEmbedUnimplementedKairosServiceServer() {}
func (UnimplementedKairosServiceServer) testEmbeddedByValue()                       {}

// UnsafeKairosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KairosServiceServer will
// result in compilation errors.
type UnsafeKairosServiceServer interface {
	mustEmbedUnimplementedKairosServiceServer()
}

func RegisterKairosServiceServer(s grpc.ServiceRegistrar, srv KairosServiceServer) {
	// If the following call panics, it indicates UnimplementedKairosServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KairosService_ServiceDesc, srv)
}

func _KairosService_Enqueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KairosServiceServer).Enqueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KairosService_Enqueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KairosServiceServer).Enqueue(ctx, req.(*EnqueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KairosService_GetQueueDepth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueueDepthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KairosServiceServer).GetQueueDepth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KairosService_GetQueueDepth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KairosServiceServer).GetQueueDepth(ctx, req.(*GetQueueDepthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KairosService_ListDeadLetter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeadLetterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KairosServiceServer).ListDeadLetter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KairosService_ListDeadLetter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KairosServiceServer).ListDeadLetter(ctx, req.(*ListDeadLetterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KairosService_RequeueDeadLetter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequeueDeadLetterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KairosServiceServer).RequeueDeadLetter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KairosService_RequeueDeadLetter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KairosServiceServer).RequeueDeadLetter(ctx, req.(*RequeueDeadLetterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KairosService_ServiceDesc is the grpc.ServiceDesc for KairosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KairosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kairos.v1.KairosService",
	HandlerType: (*KairosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enqueue",
			Handler:    _KairosService_Enqueue_Handler,
		},
		{
			MethodName: "GetQueueDepth",
			Handler:    _KairosService_GetQueueDepth_Handler,
		},
		{
			MethodName: "ListDeadLetter",
			Handler:    _KairosService_ListDeadLetter_Handler,
		},
		{
			MethodName: "RequeueDeadLetter",
			Handler:    _KairosService_RequeueDeadLetter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/kairos/v1/kairos.proto",
}
